on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: create release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@master
      - name: install dependencies
        run: sudo apt install -y zip
      - name: build the project
        run: make
      - name: upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.zip'
